# Generated by Django 3.2 on 2021-05-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='orderid',
        ),
    ]
