# Generated by Django 3.2 on 2021-05-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='PinCode',
            field=models.IntegerField(default=10),
        ),
    ]
